DATASET: 'demo'
BATCH_SIZE: 1
SAVE_SCENE_MESH: True
SAVE_INCREMENTAL: True
SAVE_FREQ: 5
MODE: 'test'
LOGDIR: './checkpoints'

RTMP_SERVER: "rtmp://127.0.0.1:1935/stream/test3" # your rtmp server URL
POSE_SERVER: 'http://172.20.10.1:9000/pose' # your logger URL, which is `ipad_IP:9000/pose`

TEST:
  N_VIEWS: 9
  N_WORKERS: 1

MODEL:
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  LW: [1.0, 0.8, 0.64]

  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5

